#!/usr/bin/env node
// Scans `public/heroes` and regenerates `src/lib/heroesManifest.ts` so new
// hero images are picked up without manually editing an array. Run via
// `npm run heroes:sync` (also runs automatically before dev/build).

import { readdirSync, writeFileSync } from 'node:fs'
import { extname, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const heroesDir = join(__dirname, '..', 'public', 'heroes')
const outputFile = join(__dirname, '..', 'src', 'lib', 'heroesManifest.ts')

const IMAGE_EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif', '.gif'])

function listHeroUrls() {
  return readdirSync(heroesDir)
    .filter((name) => IMAGE_EXTENSIONS.has(extname(name).toLowerCase()))
    .sort((a, b) => a.localeCompare(b))
    .map((name) => `/heroes/${name}`)
}

const heroes = listHeroUrls()

const contents = `// Generated by \`npm run heroes:sync\` — do not edit by hand.
// Lists every image file found in \`public/heroes\` at generation time.

export const HEROES: string[] = ${JSON.stringify(heroes, null, 2)}
`

writeFileSync(outputFile, contents)

console.log(`heroes:sync — wrote ${heroes.length} hero(es) to src/lib/heroesManifest.ts`)
if (heroes.length === 0) {
  console.warn('heroes:sync — no images found in public/heroes')
}
